[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="indexTime" type="java.lang.String" file="templates/message.ftl" --]
[#-- @ftlvariable name="page.content" type="java.lang.String" file="templates/searchResult.ftl" --]
[#-- @ftlvariable name="query" type="java.lang.String" file="templates/message.ftl" --]
[#-- @ftlvariable name="statusSuccess" type="java.lang.String" file="templates/message.ftl" --]
[#-- @ftlvariable name="statusError" type="java.lang.String" file="templates/message.ftl" --]
[#-- @ftlvariable name="query" type="java.lang.String" file="templates/searchResult.ftl" --]
[#-- @ftlvariable name="appName" type="java.lang.String" file="templates/searchResult.ftl" --]
[#-- @ftlvariable name="pages" type="java.util.Collection<com.ghost.lucene.search.SearchDocument>" file="templates/searchResult.ftl" --]
[#-- @ftlvariable name="resultCount" type="java.lang.Number" file="templates/searchResult.ftl" --]
[#-- @ftlvariable name="appName" type="java.lang.String" file="templates/search.ftl" --]
[#-- @ftlvariable name="indexCount" type="java.lang.Number" file="templates/message.ftl" --]
[#-- @ftlvariable name="query" type="java.lang.String" file="templates/index.ftl" --]
